### ISSUE TITLE
Trees break compactmachines walls

### ISSUE THREAD

**Issue by HanatakeYurii** [thraaawn/CompactMachines#115]
A friend tried to grow a sacred rubber sappling (MineFactoryReloaded) and it broke the walls letting us to go out in the compact dimension.

Edit: forgot to say that we use the latest build at this date with Forge 1352

**Comment by XFactHD** [comment]
I think this is a vanilla bug. You can also break the bedrock in the nether with a tree in vanilla minecraft.

**Comment by HanatakeYurii** [comment]
Yeah, it's fairly possible. This it's not possible to do anything, if I'm not wrong

**Comment by thraaawn** [comment]
As you already said, i don't think there is much I can do about it. Looks like MFR is not properly checking whether leaves can break the blocks, see [canBeReplacedByLeaves](https://github.com/thraaawn/CompactMachines/blob/master/src/main/java/org/dave/CompactMachines/block/BlockProtected.java#L57).
Should be reported to [MFR](https://github.com/skyboy/MineFactoryReloaded/). Already aware of this, @skyboy?

**Comment by skyboy** [comment]
The enchanted sacred rubber tree doesn't remotely consider that: it is world-destructive to grow, save bedrock. I'd suggest filling the entire dimension with some indestructible block instead of air (since you have no windows/transparency, bedrock is fine). This won't stop other trees, like the vanilla dark oak tree, from breaking out chunks of bedrock but they will at least be slower.

**Comment by HanatakeYurii** [comment]
Erm, sorry, I made a mistake.
It was not a sacred rubber, but justa big one (I disabled sacred on my server since the beginning, si it couldn't be this one.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
