### ISSUE TITLE
Allow respawning in CMs if there is no bed in the players current dim

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/CompactMachines#120]
Must be enabled via config option, default is off.

**Comment by Badcholo** [comment]
I second that, i would like to set my bed inside there. It is a personal shrinking device, not a void or ender alternate universe that doesn't allow certain things to happen such as setting your home there. I do wish there was a way to block players from being able to /home from a plugin without giving them wither and nausea. Possibly teleporting them to spawn more prefferable essentials spawn. EMobile phone mod allows you to teleport to your bed as well, but that is an advanced device so i'll just say it has a personal shinking device built into it.

**Comment by thraaawn** [comment]
@Badcholo, you can change the allowEnterWithoutPSD option in the CM config.
```Allow players to enter Compact Machines by other means than a PSD. Gives wither effect and nausea if disallowed. [default: false]```

**Comment by thraaawn** [comment]
Currently the vanilla spawn mechanics do not make you change dimensions on death, i.e. even if you allow beds in the CM dimension you only spawn there if you die in the CM dimension. This is not trivial to fix and would require ASM as far as I can tell. :-1:

**Comment by Badcholo** [comment]
Yes i had already changed the config so that players don't die when they enter the compact machine by using /home. My players upon death spawn at /spawn or the hub. Well it's a hospital technically, but it's at spawn. The mechanics of the bed are very useful by other mods like Emobile. I can sleep in my bed and i can use the phone to teleport to my bed as i please or to other authorized players. This is the only reason for  wanting to allow players to set their bed inside as it's like their own bedroom in a block. Their sleep chamber. Their own little place of decoration or heaven.

**Comment by Badcholo** [comment]
Thank you so much for such a great mod!! Everyone Really loves it.

**Comment by Badcholo** [comment]
Changed my mind. I think i'm going to set the server to require the psd to get inside of it. It works best that way.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
