### ISSUE TITLE
Compact Machine on server with plugins

### ISSUE THREAD

**Issue by landerf** [thraaawn/CompactMachines#155]
Hi guys, i have on a server compact machine and if we roght click on a compact machine with personal  Shrinking device, but we spawn in a void world and we are tp at overworld, how fix this? server have some plugins,... :/

**Comment by Badcholo** [comment]
What kind of server? cauldron? what version?
What version of the mod?
Is this a clean install? 
do you have a void2spawn plugin?
Server logs?
Did you place this block in overworld or a world created with like Multiworld?

**Comment by landerf** [comment]
It's a hermitcraft modsauce 2 server, so i don't think this, i go signal this at creater of thiss erver and i deliver to you some reponse of your ask

**Comment by Badcholo** [comment]
Did they finally update mutant creatures so it doesn't crash your server ever so often with the mutant enderman or skeleton?
i would have to download the launcher to see what version it is. 
I will when i get home.

**Comment by babyblasphemy** [comment]
Setting load-chunk-on-request to true in the cauldron.yml file should fix this issue, however it infrequently causes the server to crash.

**Comment by Badcholo** [comment]
I have had Setting load-chunk-on-request to true for years, It does not cause the server to frequently crash. Then again i do have some good plugins to help with chunk loading/unloading. 
I think it's default to set it to true.

**Comment by Badcholo** [comment]
I think this is maily cause it's an outdated modpack.

**Comment by landerf** [comment]
on my server all people say: if we turn on compact machine the server was
crash with all player on this server. the server is Isolonice if you would
like come.

2015-10-17 18:08 GMT+02:00 Badcholo <notifications@github.com>:

**Comment by Badcholo** [comment]
sure thing is there a specific ip?

**Comment by Badcholo** [comment]
The modpack is using currently the latest version. 
compactmachines-1.7.10-1.20
it is using some core mods in alpha thou.
such as CoFHCore-[1.7.10]3.0.4B1-308
I tried it in single player and used everything in CM and found no issues. 
There must be corrupt files on the server somewhere that is causing the issues.
You should try a clean install. I would talk to the modpack creator and see if he has tested his pack on a server. Also talk to the server owner and see if he can make a clean install and try that out.
I have had issues, but it was due to corrupt files.
making a clean install fixed my issues.

**Comment by thraaawn** [comment]
https://github.com/thraaawn/CompactMachines/issues/93#issuecomment-94880005
