### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by pascaldulieu** [thraaawn/CompactMachines#162]
CM - Compact Machines
CC - Computer craft
PC - Pneumatic Craft

The game crashes on startup when running with Computer craft, Pneumatic craft and Compact Machines.

The game will run if CM and CC or CM and PC or CC and PC are together but will not run at all 3 are running at the same time.

[Mod Pack crash log](http://pastebin.com/7cFhusTG)

[Isolated mods crash log](http://pastebin.com/pQ0nABJ4)

Compact machines 1.20 works with all the mods but it will crash on CM 1.21

**Comment by bochen415** [comment]
Just add OpenComputers and it will work just fine...
I'm not kidding here

**Comment by pascaldulieu** [comment]
Will all computer craft programs work 100% with opencomputers and what is the difference between the two?

**Comment by khionu** [comment]
He's saying your 3 + OpenComputers. Just don't use OC

**Comment by bochen415** [comment]
That I can't guarantee but it will certainly not crash at startup, worth testing

**Comment by pascaldulieu** [comment]
I did add at the bottom that the crash only occurs on the latest version (1.21) but it works fine on 1.20

**Comment by khionu** [comment]
I'll diff them, see what was changed.

**Comment by khionu** [comment]
Also, about the programs, no, they would not be 100% compatible, however, if you wanted to use OC instead of CC, it shouldn't be that big of an adaptation.

**Comment by pascaldulieu** [comment]
Do the two mods work along side each other?

**Comment by thraaawn** [comment]
The problem seems to be the following:
* Mods are loaded alphabetically unless otherwise defined in their Mod annotation.
* PneumaticCraft uses ComputerCraft if it is available, but does not specify that it needs to load after it.
* CompactMachines wants to be loaded after PneumaticCraft if it is available, which seems to move PneumaticCraft to the front of the list with ComputerCraft still being behind CompactMachines, i.e. when all three Mods are active they load in this order:
  1. PneumaticCraft
  2. CompactMachines
  3. ComputerCraft
* This throws PneumaticCraft of the rails, because it tries to use ComputerCraft without it being loaded yet.

Solution: add ``after:ComputerCraft`` to the dependencies of PneumaticCraft.
I'll open a pull request on PneumaticCraft.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
